language: python

#sudo: false

#addons:
#  apt:
#    packages:
#    - build-essential
#    - python-dev
#    - openssl
#    - libssl-dev
#    - libevent-dev

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential python-dev openssl libssl-dev libevent-dev
  - sudo ./services/core/MongodbHistorian/tests/mongosetup.sh
  - python setup.py install

script: scripts/run-tests.sh

#language: python
#matrix:
#  include:
#    - python: "2.7"
#      env: TEST_SUITE=suite_2_7
# script: env/bin/python
