language: python

dist: trusty
sudo: required
#sudo: false

#addons:
#  apt:
#    packages:
#    - build-essential
#    - python-dev
#    - openssl
#    - libssl-dev
#    - libevent-dev

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential python-dev openssl libssl-dev libevent-dev
  - ./services/core/MongodbHistorian/tests/mongosetup.sh

install:
  - python2 bootstrap.py

script: scripts/run-tests.sh

notifications:
  email:
    craig.allwardt@pnnl.gov
    zachary.beech@pnnl.gov
    jereme.haack@pnnl.gov
    kyle.monson@pnnl.gov
    joseph.chapman@pnnl.gov
    poorva.sharma@pnnl.gov
    michael.roup@pnnl.gov
    bora.akyol@pnnl.gov
    robert.lutes@pnnl.gov

#language: python
#matrix:
#  include:
#    - python: "2.7"
#      env: TEST_SUITE=suite_2_7
# script: env/bin/python
