language: python

#sudo: false

#addons:
#  apt:
#    packages:
#    - build-essential
#    - python-dev
#    - openssl
#    - libssl-dev
#    - libevent-dev
services:
  - mongodb

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential python-dev openssl libssl-dev libevent-dev
  - python setup.py install

before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.8.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-3.0.8/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --auth &> /dev/null &
  - ${PWD}/mongodb-linux-x86_64-3.0.8/bin/mongo < services/coreMongodbHistorian/tests/mongodb.init.js

script: scripts/run-tests.sh

#language: python
#matrix:
#  include:
#    - python: "2.7"
#      env: TEST_SUITE=suite_2_7
# script: env/bin/python
